// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID
	Title     string
	Username  string
	Text      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	Username string
	Password string
	Email    string
}
